name = "bluesky-pso2ngs-resets"
main = "./src/index.ts"
compatibility_date = "2023-09-04"

[triggers]
crons = ["0 12 * * *", "0 3 * * 3"]

[vars]
BLUESKY_SERVICE = "https://bsky.social"
BLUESKY_USERNAME = "pso2ngs-resets.bsky.social"
